### ISSUE TITLE
Mod crashes server on using /home command

### ISSUE THREAD

**Issue by wiesshund** [MrSn0wy/TeleportCommands#3]
Here is the server and crash log.
It sets and saves homes fine

[crash-2024-11-17_21.38.21-server.txt](https://github.com/user-attachments/files/17793951/crash-2024-11-17_21.38.21-server.txt)

[latest.log](https://github.com/user-attachments/files/17793927/latest.log)

**Comment by MrSn0wy** [comment]
Hey it seems you are using 1.21.3, that version changed something with the teleporting that causes it to crash.

If you want you can use this updated version in the meantime that i havent uploaded on modrinth yet: https://github.com/MrSn0wy/TeleportCommands/actions/runs/11797357856
On the bottom of the page download the Artifacts and then extract it locally, then get the jar for your mod loader in one of the folders.

I will upload it on modrinth in a few days, i was working on improving the error handling so i didnt release it yet

**Comment by wiesshund** [comment]
I did test your unreleased one
It did work fine, no issues that I saw

**Comment by wiesshund** [comment]
Not sure if it is possible to do easy
But i was thinking that it might be neat if one could set a few global destinations as an admin
that normal players could then use.

like to recall to world spawn
or a few other areas if the server has some set up
they could like type /goto <location>

be up to the ops to make the locations known.

I like that his mod doesnt need world objects and resource packs etc

**Comment by MrSn0wy** [comment]
> I did test your unreleased one It did work fine, no issues that I saw

Awesome!

> Not sure if it is possible to do easy But i was thinking that it might be neat if one could set a few global destinations as an admin that normal players could then use.
> 
> like to recall to world spawn or a few other areas if the server has some set up they could like type /goto
> 
> be up to the ops to make the locations known.

I really like that idea, currently working on implementing it and thinking of just naming it ``/warp``, shouldn't be too difficult. Will try to make a release with it today!

**Comment by MrSn0wy** [comment]
Hey sorry for saying i would finish it in a day heh~

Some stuff came in between, howeve i have added a /warp and a /worldspawn command to the mod!

**Comment by MrSn0wy** [comment]
Gonna close the issue now
